rpm/lipstick-glacier-home-qt5.spec, rpm/lipstick-glacier-home-qt5.yaml, src/qml/AppLauncher.qml, src/qml/DeviceLock.qml, src/qml/Lockscreen.qml, src/qml/NumButton.qml, src/qml/SimPanel.qml, src/qml/compositor.qml, src/src.pro
* Device lock
* Sim panel has reasonable buttons
* Label renames as per @Sfiet_Konstantin
=> Version 0.25

src/qml/Statusbar.qml, src/qml/StatusbarItem.qml
=> [scaling] Scaling of statusbar

rpm/lipstick-glacier-home-qt5.spec, src/i18n/glacer-home.ts, src/qml/AppLauncher.qml, src/qml/AppSwitcher.qml, src/qml/BatteryPanel.qml, src/qml/CommonPanel.qml, src/qml/DeviceLock.qml, src/qml/DeviceLockUI.qml, src/qml/LauncherItemDelegate.qml, src/qml/Lockscreen.qml, src/qml/MainScreen.qml, src/qml/SimPanel.qml, src/qml/USBModeSelector.qml, src/qml/compositor.qml, src/src.pro
* Add Internationalization support
* Lockscreen work on sailfish > 2.0.4
* Lockscreen styles
=> Code update

.gitignore, src/qml/AppLauncher.qml, src/qml/AppSwitcher.qml, src/qml/DeviceLockUI.qml, src/qml/FeedsPage.qml, src/qml/LauncherItemDelegate.qml, src/qml/LauncherItemFolder.qml, src/qml/LauncherItemWrapper.qml, src/qml/Lockscreen.qml, src/qml/LockscreenClock.qml, src/qml/MainScreen.qml, src/qml/SearchListView.qml, src/qml/Statusbar.qml, src/qml/compositor.qml, src/qml/notifications/NotificationItem.qml, src/qml/notifications/NotificationPreview.qml, src/qml/statusbar/BatteryIndicator.qml, src/qml/statusbar/BatteryPanel.qml, src/qml/statusbar/CommonPanel.qml, src/qml/statusbar/SimPanel.qml, src/qml/statusbar/StatusbarItem.qml, src/qml/statusbar/WifiPanel.qml, src/src.pro
Finalized perfect folder support with icons, Search bar on top of AppLauncher, fix FeedsPage, StatusBar almost up to spec and more..
Depends on https://github.com/nemomobile/qtquickcontrols-nemo/pull/45 InverseMouseArea
More info in commit messages.
=> Applauncher improvements

src/qml/AppLauncher.qml, src/qml/DeviceLockUI.qml, src/qml/LauncherItemDelegate.qml, src/qml/LauncherItemFolder.qml, src/qml/LauncherItemWrapper.qml, src/qml/Lockscreen.qml, src/qml/MainScreen.qml, src/qml/SearchListView.qml, src/qml/Statusbar.qml, src/qml/compositor.qml, src/qml/notifications/NotificationItem.qml, src/qml/statusbar/StatusbarItem.qml
Add iconSizeLauncher to be able to have scalable AppLauncher. Also devicelock improvements.
Depends on https://github.com/nemomobile/qtquickcontrols-nemo/pull/48
=> [AppLauncher] Add IconSizeLauncher

src/qml/AppLauncher.qml, src/qml/AppSwitcher.qml, src/qml/DeviceLockUI.qml, src/qml/FeedsPage.qml, src/qml/LockscreenClock.qml, src/qml/SearchListView.qml, src/qml/SwitcherItem.qml, src/qml/notifications/NotificationItem.qml, src/qml/notifications/NotificationPreview.qml, src/qml/statusbar/CommonPanel.qml, src/qml/statusbar/WifiPanel.qml
Now the Theme.fontSizes are really small if scalable pixelSize is used, request to change that.
We should use pixelSize since pointSize is not really reliable on scaling.
Depends on https://github.com/nemomobile/qtquickcontrols-nemo/pull/49
=> [Scaling] Request to change fontSize to font.pixelSize

src/qml/AppLauncher.qml, src/qml/AppSwitcher.qml, src/qml/MainScreen.qml, src/qml/SearchListView.qml, src/qml/SwitcherItem.qml, src/qml/statusbar/BatteryPanel.qml, src/qml/statusbar/CommonPanel.qml, src/qml/statusbar/SimPanel.qml, src/qml/statusbar/WifiPanel.qml
Add fontawesome icons to Launcher, fix minimized app rotation on AppSwitcher, add powersave options to statusbar.
=> [AppLauncher] Fixes and improvements for homescreen and statusbar

src/qml/AppLauncher.qml, src/qml/AppSwitcher.qml, src/qml/FeedsPage.qml, src/qml/LauncherItemDelegate.qml, src/qml/Lockscreen.qml, src/qml/LockscreenClock.qml, src/qml/SearchListView.qml, src/qml/Statusbar.qml, src/qml/SwitcherItem.qml, src/qml/notifications/NotificationItem.qml, src/qml/notifications/NotificationPreview.qml, src/qml/statusbar/BatteryIndicator.qml, src/qml/statusbar/CommonPanel.qml, src/qml/statusbar/StatusbarItem.qml, src/qml/statusbar/WifiPanel.qml
Add timestamp to notification, possibility to dismiss notification and try to fix missing icons in notifications.
Possibility to search inside of folders in homescreen search.
Minor updates and fixes all over homescreen.
=> [Scaling][Notification][Search] Fix scaling to use newly calculated Theme.sizes

glacier-home.pro, src/glacierwindowmodel.cpp, src/main.cpp, src/qml/AppLauncher.qml, src/qml/GlacierRotation.qml, src/qml/Lockscreen.qml, src/qml/MainScreen.qml, src/qml/applauncher/LauncherItemWrapper.qml, src/qml/applauncher/SearchListView.qml, src/qml/appswitcher/SwitcherItem.qml, src/qml/compositor.qml, src/qml/compositor/ScreenGestureArea.qml, src/qml/compositor/WindowWrapperAlpha.qml, src/qml/compositor/WindowWrapperBase.qml, src/qml/compositor_new.qml, src/qml/lockscreen/DeviceLockUI.qml, src/qml/mainscreen/Wallpaper.qml, src/qml/statusbar/BatteryIndicator.qml, src/qml/system/Screenshot.qml
**Update to Qt5.12**  
CodePadUi needs fixing - doesn't appear at all  
Lockscreen needs fixing - swipes are funny & can't lock it after unlocking  
Icon movement & Folders need fixing - @neochapay has pull request and I can do a fix.
=> Add Qt5.12 support 

src/qml/dialogs/UsbModeDialog.qml, translations/glacer-home.ts, translations/glacer-home_nl.ts, translations/glacer-home_ru.ts
I'm sure there can be some better translations, but this is a good first effort and people can improve it later on :wink:
=> [i18n] Add Dutch translations

rpm/lipstick-glacier-home-qt5.spec
@neochapay: Not merging myself, as I don't know how far are you with local development. Feel free to close request and add to your own copy. Mainly pushing here as a reminder
=> Add nemo-qml-plugin-contacts-qt5 to the requirements

CMakeLists.txt, rpm/lipstick-glacier-home-qt5.spec
Fix install of service files on 64-bit arch
=> Specify unitdir for installation

src/main.cpp
=> fix loading of translations

src/qml/GlacierCompositor.qml, src/qml/Lockscreen.qml, src/qml/MainScreen.qml, src/qml/lockscreen/DeviceLockUI.qml, src/qml/mainscreen/Wallpaper.qml, src/qml/notifications/NotificationItem.qml, src/qml/notifications/NotificationPreview.qml, src/qml/scripts/desktop.js, src/qml/volumecontrol/VolumeControl.qml
Use global values like Desktop.instance it bad practice
=> Don't use global values

src/qml/FeedsPage.qml, src/qml/feedspage/BluetoothControlButton.qml, src/qml/feedspage/CellularDataControlButton.qml, src/qml/feedspage/ControlButton.qml, src/qml/feedspage/ControlCenter.qml, src/qml/feedspage/LocationControlButton.qml, src/qml/feedspage/QuietControlButton.qml, src/qml/feedspage/WiFiControlButton.qml, src/qml/notifications/NotificationItem.qml
=> [FeedsPage] Update desigin

src/qml/feedspage/BluetoothControlButton.qml
see f081ed3e7c667e0daf6b0b8cf4e72fe2ffa25f4d
=> updateLabel function was removed during design update 

settings-plugins/desktop/desktop.qml, src/CMakeLists.txt, src/qml/MainScreen.qml, src/qml/mainscreen/Pager.qml
Fixes https://github.com/nemomobile-ux/main/issues/27
=> Iteration 2: Allow infinity scrolling of main screen.

settings-plugins/desktop/desktop.qml, src/qml/GlacierCompositor.qml
I am not sure if it works properly.
=> Disable animation in settings

settings-plugins/desktop/desktop.qml, settings-plugins/wallpaper/selectImage.qml, settings-plugins/wallpaper/wallpaper.qml, src/qml/GlacierCompositor.qml
see https://github.com/sailfishos/nemo-qml-plugin-configuration/commit/cab528e3ebfc05bc5d025376cc614df3372dddf1
=> Use Nemo.Configuration instead of deprecated one

src/qml/feedspage/BluetoothControlButton.qml, src/qml/notifications/NotificationItem.qml
The Summary and Preview wasn't visible due to overflow. The dimensions of element wasn't computed properly.
```
notify-send -a "lipstick" -i "icon-system-charging" "summary summary summary" "body body body body body"
notify-send -a "lipstick" -i "icon-system-usb" "summary summary summary" "body body body body body"
notify-send -a "lipstick" -i "bluetooth" "some device is near" "body body body body body"
notify-send -i "cat" -a "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore" \
"et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo" \
"consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
```
=> rework notifications
